theme: jekyll-theme-minimal
title: [Hamed Nazari Personal Webpage]
description: [Hello there, this is my personal webpage.]
logo: [me.jpg]
show_downloads: ["true" or "false" to indicate whether to provide a download URL]
